### ISSUE TITLE
install error idealTree already exists

### ISSUE THREAD

**Issue by pwFoo** [draeder/easypeers#15]
Hi,

install failed inside of node:alpine and node:lts-alpine containers:
```
/ # npm i easypeers
npm ERR! Tracker "idealTree" already exists

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-17T18_36_13_919Z-debug-0.log
```

debug log
```
36 timing idealTree:userRequests Completed in 14ms
37 silly idealTree buildDeps
38 timing idealTree Completed in 31ms
39 timing command:i Completed in 276ms
40 verbose stack Error: Tracker "idealTree" already exists
40 verbose stack     at [_onError] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/tracker.js:100:11)
40 verbose stack     at Arborist.addTracker (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/tracker.js:27:21)
40 verbose stack     at [buildDeps] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:775:10)
40 verbose stack     at Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:29)
40 verbose stack     at async Promise.all (index 1)
40 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
40 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:146:5)
40 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:134:5)
```

**Comment by draeder** [comment]
Thanks for reporting the issue. I have not tested the codebase with Docker yet. You may want to upgrade to the latest commit. There was a pretty critical error in the code that was not honoring passed in topics that has been resolved in the latest.
